In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [6]:
X = iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y= iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from keras.utils import to_categorical
y= to_categorical(y)

Using TensorFlow backend.


In [11]:
y.shape

(150, 3)

In [12]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =    train_test_split(X,y,test_size=0.33,random_state=42)

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

## Now we are ready to call the neural network model from keras

In [15]:
from keras.models import Sequential
from keras.layers import Dense

## First create a sequential model and then add layers to it

In [17]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax')) ### Number of classes which are already in numpy format and 3 by 150 shape 
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
### lossis really about the problem pou are trying to solve

In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(scaled_X_train, y_train, epochs=150,verbose=2)

Epoch 1/150
 - 1s - loss: 1.1475 - acc: 0.0500
Epoch 2/150
 - 0s - loss: 1.1336 - acc: 0.2800
Epoch 3/150
 - 0s - loss: 1.1204 - acc: 0.3400
Epoch 4/150
 - 0s - loss: 1.1087 - acc: 0.3400
Epoch 5/150
 - 0s - loss: 1.0953 - acc: 0.3400
Epoch 6/150
 - 0s - loss: 1.0840 - acc: 0.3400
Epoch 7/150
 - 0s - loss: 1.0742 - acc: 0.3500
Epoch 8/150
 - 0s - loss: 1.0667 - acc: 0.3500
Epoch 9/150
 - 0s - loss: 1.0610 - acc: 0.3500
Epoch 10/150
 - 0s - loss: 1.0566 - acc: 0.3300
Epoch 11/150
 - 0s - loss: 1.0521 - acc: 0.3400
Epoch 12/150
 - 0s - loss: 1.0478 - acc: 0.3800
Epoch 13/150
 - 0s - loss: 1.0437 - acc: 0.3500
Epoch 14/150
 - 0s - loss: 1.0405 - acc: 0.3400
Epoch 15/150
 - 0s - loss: 1.0373 - acc: 0.3400
Epoch 16/150
 - 0s - loss: 1.0346 - acc: 0.3400
Epoch 17/150
 - 0s - loss: 1.0319 - acc: 0.3400
Epoch 18/150
 - 0s - loss: 1.0289 - acc: 0.3400
Epoch 19/150
 - 0s - loss: 1.0262 - acc: 0.3400
Epoch 20/150
 - 0s - loss: 1.0232 - acc: 0.3400
Epoch 21/150
 - 0s - loss: 1.0201 - acc: 0.3400
E

## Lets feed scaled_X_test to the model

In [22]:
model.predict(scaled_X_test)  ### this gives the soft probabilities 

array([[0.05254806, 0.42669287, 0.520759  ],
       [0.43990028, 0.33372506, 0.22637472],
       [0.00335962, 0.27071404, 0.72592634],
       [0.04864199, 0.40521955, 0.54613847],
       [0.03192015, 0.40185496, 0.56622493],
       [0.45744765, 0.3269463 , 0.21560612],
       [0.09933446, 0.43092754, 0.46973792],
       [0.01350869, 0.31147584, 0.6750155 ],
       [0.03589595, 0.42454332, 0.53956074],
       [0.08191957, 0.44188303, 0.47619742],
       [0.0215238 , 0.33899242, 0.6394837 ],
       [0.47055012, 0.3109637 , 0.2184862 ],
       [0.46800366, 0.31474876, 0.21724758],
       [0.47080058, 0.31092787, 0.21827155],
       [0.47831672, 0.29915538, 0.22252785],
       [0.04091027, 0.37896746, 0.58012223],
       [0.01211863, 0.31205454, 0.67582685],
       [0.08983364, 0.45533413, 0.45483214],
       [0.06249768, 0.425315  , 0.5121873 ],
       [0.01309927, 0.3228209 , 0.66407984],
       [0.47611538, 0.3031969 , 0.2206878 ],
       [0.03124436, 0.3700364 , 0.5987193 ],
       [0.

In [23]:
model.predict_classes(scaled_X_test)

array([2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)

## Compare predictions with y_test

In [24]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [25]:
predictions = model.predict_classes(scaled_X_test)

In [26]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [28]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0,  2, 13],
       [ 0,  0, 16]], dtype=int64)

In [31]:
classification_report(y_test.argmax(axis=1),predictions)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        19\n           1       1.00      0.13      0.24        15\n           2       0.55      1.00      0.71        16\n\n   micro avg       0.74      0.74      0.74        50\n   macro avg       0.85      0.71      0.65        50\nweighted avg       0.86      0.74      0.68        50\n'

In [32]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.74

In [33]:
model.save('NNbasicModel.h5')

In [34]:
from keras.models import load_model
new_model = load_model('NNbasicModel.h5')